### ISSUE TITLE
"New Project" and "New ToDo" arrow icons do not switch back to correct direction on pressing "save"

### ISSUE THREAD

**Issue by digidub** [Tzar2nd/to-do-list#1]
If you enter a new Project or ToDo, the form disappears however the arrow icon does not switch back to the correct direction, creating an inverse toggle.

**Comment by Tzar2nd** [comment]
Resolved by updating the code to redirect to include the arrow icon method. This was already working when clicking the button itself but not when clicking Cancel or Save.

**Comment by Tzar2nd** [comment]
In addition: 
* Resolved the ticks they were the wrong way around and ticked = complete and are now greyed out when ticked.
* Removed the numbers from the priority system so to users 1, 2 and 3 are just red (high), orange (medium),  and green(low) priority.

**Comment by Tzar2nd** [comment]
Resolved
